#############################################################################
# Makefile for building: Qt5_CinematicExperience
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  Qt5_CinematicExperience.pro
# Template: app
# Command: /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake -o Makefile Qt5_CinematicExperience.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = aarch64-poky-linux-gcc  --sysroot=/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux
CXX           = aarch64-poky-linux-g++  --sysroot=/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NO_QML_DEBUGGER -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5 -isystem /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick -isystem /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui -isystem /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml -isystem /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtNetwork -isystem /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore -I. -I/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Qt5_CinematicExperience1.0.0
DISTDIR = /home/work/dk/imx8m/projects/rootfs/Qt5_CinematicExperience_rpi_1.0/.tmp/Qt5_CinematicExperience1.0.0
LINK          = aarch64-poky-linux-g++  --sysroot=/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux
LFLAGS        = -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed --sysroot=/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lEGL -lpthread 
AR            = aarch64-poky-linux-ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resources.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/moc.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf \
		Qt5_CinematicExperience.pro  main.cpp
QMAKE_TARGET  = Qt5_CinematicExperience
DESTDIR       = 
TARGET        = Qt5_CinematicExperience


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qt5_CinematicExperience.pro /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resources.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/moc.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf \
		Qt5_CinematicExperience.pro \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Quick.prl \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Gui.prl \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Qml.prl \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Network.prl \
		/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Qt5_CinematicExperience.pro
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resources.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/moc.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf:
Qt5_CinematicExperience.pro:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Quick.prl:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Gui.prl:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Qml.prl:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Network.prl:
/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Qt5_CinematicExperience.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/data/dummy.cpp
	aarch64-poky-linux-g++  --sysroot=/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -O2 -Wall -W -dM -E -o moc_predefs.h /home/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Qt5_CinematicExperience || mkdir -p $(INSTALL_ROOT)/opt/Qt5_CinematicExperience
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Qt5_CinematicExperience/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Qt5_CinematicExperience/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Qt5_CinematicExperience/ 


install_qml: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Qt5_CinematicExperience || mkdir -p $(INSTALL_ROOT)/opt/Qt5_CinematicExperience
	-$(INSTALL_FILE) /home/work/dk/imx8m/projects/rootfs/Qt5_CinematicExperience_rpi_1.0/Qt5_CinematicExperience.qml $(INSTALL_ROOT)/opt/Qt5_CinematicExperience/
	-$(INSTALL_DIR) /home/work/dk/imx8m/projects/rootfs/Qt5_CinematicExperience_rpi_1.0/content $(INSTALL_ROOT)/opt/Qt5_CinematicExperience/

uninstall_qml: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Qt5_CinematicExperience/content
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Qt5_CinematicExperience/Qt5_CinematicExperience.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Qt5_CinematicExperience/ 


install: install_target install_qml  FORCE

uninstall: uninstall_target uninstall_qml  FORCE

FORCE:

