#############################################################################
# Makefile for building: Qt5_EmcraftDemo
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  Qt5_EmcraftDemo.pro
# Template: app
# Command: /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake -o Makefile Qt5_EmcraftDemo.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = aarch64-poky-linux-gcc  --sysroot=/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux
CXX           = aarch64-poky-linux-g++  --sysroot=/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NO_QML_DEBUGGER -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5 -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtNetwork -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore -I. -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Qt5_EmcraftDemo1.0.0
DISTDIR = /home/alex/work/emc_repos/qmldemo/.tmp/Qt5_EmcraftDemo1.0.0
LINK          = aarch64-poky-linux-g++  --sysroot=/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux
LFLAGS        = -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed --sysroot=/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -Wl,-O1
LIBS          = $(SUBLIBS) -L/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib -lQt5Quick -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lEGL -lpthread 
AR            = aarch64-poky-linux-ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		launcher.cpp moc_launcher.cpp
OBJECTS       = main.o \
		launcher.o \
		moc_launcher.o
DIST          = /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf \
		Qt5_EmcraftDemo.pro launcher.h main.cpp \
		launcher.cpp
QMAKE_TARGET  = Qt5_EmcraftDemo
DESTDIR       = 
TARGET        = Qt5_EmcraftDemo


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Qt5_EmcraftDemo.pro /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf \
		Qt5_EmcraftDemo.pro \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Quick.prl \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Gui.prl \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Qml.prl \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Network.prl \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Qt5_EmcraftDemo.pro
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/unix.conf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/linux.conf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/sanitize.conf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-base.conf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/oe-device-extra.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qdevice.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/device_config.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/qconfig.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_location_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt_config.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/toolchain.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_pre.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/default_post.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/warn_on.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qt.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/resources.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/moc.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/file_copies.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/exceptions.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/yacc.prf:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/lex.prf:
Qt5_EmcraftDemo.pro:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Quick.prl:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Gui.prl:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Qml.prl:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Network.prl:
/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Qt5_EmcraftDemo.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents launcher.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp launcher.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/data/dummy.cpp
	aarch64-poky-linux-g++  --sysroot=/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -pipe  -O2 -pipe -g -feliminate-unused-debug-types  --sysroot=/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux -O2 -Wall -W -dM -E -o moc_predefs.h /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_launcher.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_launcher.cpp
moc_launcher.cpp: /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QObject \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobject.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobjectdefs.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qnamespace.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qglobal.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qconfig-bootstrapped.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qconfig.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtcore-config.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsystemdetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qprocessordetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcompilerdetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtypeinfo.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsysinfo.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qlogging.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qflags.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtypetraits.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbasicatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qgenericatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_msvc.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qglobalstatic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmutex.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qnumeric.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qversiontagging.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstring.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qchar.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbytearray.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qrefcount.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qarraydata.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringbuilder.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qlist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qalgorithms.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qiterator.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qhashfunctions.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qpair.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbytearraylist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringlist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qregexp.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringmatcher.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcoreevent.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qscopedpointer.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmetatype.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qvarlengtharray.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcontainerfwd.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobject_impl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QProcess \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qprocess.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qiodevice.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qshareddata.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qhash.h \
		launcher.h \
		moc_predefs.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/moc
	/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/x86_64-pokysdk-linux/usr/bin/qt5/moc $(DEFINES) --include ./moc_predefs.h -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/alex/work/emc_repos/qmldemo -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5 -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtNetwork -I/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-redhat-linux/7/include -I/usr/local/include -I/usr/include launcher.h -o moc_launcher.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/QGuiApplication \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qguiapplication.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qtguiglobal.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qglobal.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qconfig-bootstrapped.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qconfig.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtcore-config.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsystemdetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qprocessordetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcompilerdetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtypeinfo.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsysinfo.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qlogging.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qflags.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtypetraits.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbasicatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qgenericatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_msvc.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qglobalstatic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmutex.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qnumeric.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qversiontagging.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qtgui-config.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcoreapplication.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstring.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qchar.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbytearray.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qrefcount.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qnamespace.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qarraydata.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringbuilder.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobject.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobjectdefs.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qlist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qalgorithms.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qiterator.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qhashfunctions.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qpair.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbytearraylist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringlist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qregexp.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringmatcher.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcoreevent.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qscopedpointer.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmetatype.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qvarlengtharray.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcontainerfwd.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobject_impl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qeventloop.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qwindowdefs.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qwindowdefs_win.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qinputmethod.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qlocale.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qvariant.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmap.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qdebug.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qhash.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtextstream.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qiodevice.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qvector.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qpoint.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qset.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcontiguouscache.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsharedpointer.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qshareddata.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsharedpointer_impl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsize.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick/QQuickView \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick/qquickview.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick/qquickwindow.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick/qtquickglobal.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml/qtqmlglobal.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml/qtqml-config.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtNetwork/qtnetworkglobal.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtNetwork/qtnetwork-config.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick/qtquick-config.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick/qsgrendererinterface.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick/qsgnode.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQuick/qsggeometry.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qopengl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qt_windows.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qopengles2ext.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qopenglext.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QRectF \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qrect.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmargins.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/QMatrix4x4 \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qmatrix4x4.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qvector3d.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qvector4d.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qquaternion.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qgenericmatrix.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qdatastream.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qwindow.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QObject \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QEvent \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QMargins \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QRect \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qsurface.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qsurfaceformat.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qicon.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qpixmap.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qpaintdevice.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qcolor.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qrgb.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qrgba64.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qimage.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qpixelformat.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qtransform.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qmatrix.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qpolygon.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qregion.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qline.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qpainterpath.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qcursor.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qevent.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qkeysequence.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qurl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qurlquery.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qfile.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qfiledevice.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qvector2d.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtGui/qtouchdevice.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml/qqml.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml/qqmlprivate.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml/qqmlparserstatus.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml/qqmlpropertyvaluesource.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml/qqmllist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmetaobject.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtQml/qqmldebug.h \
		launcher.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QProcess \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qprocess.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

launcher.o: launcher.cpp launcher.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QObject \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobject.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobjectdefs.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qnamespace.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qglobal.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qconfig-bootstrapped.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qconfig.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtcore-config.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsystemdetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qprocessordetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcompilerdetection.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtypeinfo.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qsysinfo.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qlogging.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qflags.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qtypetraits.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbasicatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_bootstrap.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qgenericatomic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_cxx11.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qatomic_msvc.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qglobalstatic.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmutex.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qnumeric.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qversiontagging.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobjectdefs_impl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstring.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qchar.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbytearray.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qrefcount.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qarraydata.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringbuilder.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qlist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qalgorithms.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qiterator.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qhashfunctions.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qpair.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qbytearraylist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringlist.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qregexp.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qstringmatcher.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcoreevent.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qscopedpointer.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qmetatype.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qvarlengtharray.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qcontainerfwd.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qobject_impl.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/QProcess \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qprocess.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qiodevice.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qshareddata.h \
		/opt/fsl-imx-fb/4.9.51-mx8-beta/sysroots/aarch64-poky-linux/usr/include/qt5/QtCore/qhash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o launcher.o launcher.cpp

moc_launcher.o: moc_launcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_launcher.o moc_launcher.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo || mkdir -p $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo/ 


install_qml: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo || mkdir -p $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo
	-$(INSTALL_FILE) /home/alex/work/emc_repos/qmldemo/Qt5_EmcraftDemo.qml $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo/
	-$(INSTALL_DIR) /home/alex/work/emc_repos/qmldemo/content $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo/

uninstall_qml: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo/content
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo/Qt5_EmcraftDemo.qml
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Qt5_EmcraftDemo/ 


install: install_target install_qml  FORCE

uninstall: uninstall_target uninstall_qml  FORCE

FORCE:

